# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O8lVOpy_SMapuSrI0eOQab4B6D1mQhrB
"""

def calculate_factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Get user input
number = int(input("Enter a number: "))

# Calculate and display the factorial
factorial_result = calculate_factorial(number)
print(f"The factorial of {number} is: {factorial_result}")